baseURL = 'http://urmomis.online/'
languageCode = 'en-us'
title = 'Hugo Site #1'
theme = "hugo-coder"
colorScheme = "auto"
[params]
  author = "Abhi"
  info = "13 year old developer. Big dreams."
  description = "My personal website. Yay?"
  keywords = "blog,developer,personal"
  avatarurl = "https://cdn.jsdelivr.net/gh/twitter/twemoji/assets/svg/1f978.svg"
  #gravatar = "john.doe@example.com"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false
[menu]
[[menu.main]]
  identifier = 'blog'
  name = 'Blog'
  title = 'Blog'
  url = '/blog/'
  weight = -110